import Head from "next/head";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState, useEffect } from "react";
import deved from "../public/profileImg.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/minister.png";
import web2 from "../public/searchBar.png";
import web3 from "../public/chopingApp.png";
import web4 from "../public/myadmin.png";
import web5 from "../public/Karanta.png";
import web6 from "../public/dictionnary.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  function changeColor() {
    if (darkMode) {
      document.body.style.background = "#101827";
    } else {
      document.body.style.background = "#F2F4F6";
    }
  }
  useEffect(() => {
    changeColor();
  });
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portofolio Yacos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white   dark: px-10 dark:bg-gray-900  md:px-20 lg:px-30">
        <section className="max-w-4xl min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyyacos</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1uUWoX4HEd4pZlFsNE54XI-AaT1soyjKI/view?usp=sharing"
                  target="_blank" rel='noreferrer'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Yacoubou Seidou Chaibou
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Web Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hi, you can call me
              <span className="text-teal-600"> Yacos</span> for short! I&apos;m a web
              developer with in-depth experience Web & mobile development. I was
              in self-taught for 4 years and i join a codecamp that make me
              create websites that help organizations address business
              challenges and meet their needs. My expertise lies within
              Full-stack development with the
              <span className="text-teal-600">
                {" "}
                MERN stack (MongoDb, Express, React.js, Node.js)
              </span>
              , and the main languages in my tech stack is{" "}
              <span className="text-teal-600">JavaScript</span> . I am passionate about creating robust, user-friendly web applications, and I&apos;m expanding my skills as a student at 
              <a
                className="hover:underline ml-1 text-blue-500"
                href="https://www.microverse.org/"
                target="_blank" rel='noreferrer'
              >
                Microverse
              </a>{" "}
              , a remote software development school. Love musique, games and sport.
  .
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
                href="https://www.linkedin.com/in/yacos-chaibou-961518251/"
                target="_blank" rel='noreferrer'
              >
                <AiFillLinkedin />
              </a>
              <a
                className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
                href="https://github.com/Yacoubou-seidou"
                target="_blank" rel='noreferrer'
              >
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt="profile" />
            </div>
          </div>
        </section>
        <section className="max-w-4xl">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance developer, I&apos;ve
              done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including
              <span className="text-teal-500"> web development </span>(
              <span className="text-teal-500">front-end </span> and
              <span className="text-teal-500"> back-end</span>),{" "}
              <span className="text-teal-500">programming</span> and
              <span className="text-teal-500"> app development</span>,{" "}
              <span className="text-teal-500"> API creation</span>.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="ilustration"/>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Front-End development
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Html5</p>
              <p className="text-gray-800 py-1">Css3</p>
              <p className="text-gray-800 py-1">JavaScript</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="ilustration"/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Back-end development
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website back-end? Let&apos;s
                make it a reality.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">MongoDb</p>
              <p className="text-gray-800 py-1">NoSQL</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt="ilustration"/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">Framework</h3>
              <p className="py-2">
                Did you want framework for your project? I can use many css
                framework and development one.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Node.js</p>
              <p className="text-gray-800 py-1">Express.js</p>
              <p className="text-gray-800 py-1">React.js</p>
            </div>
          </div>
        </section>
        <section className="py-10 max-w-4xl">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since i start my journey in 2018 i learned from many platform like
              <a
                className="hover:underline ml-1 text-blue-500"
                href="https://www.freecodecamp.org/learn"
                target="_blank" rel='noreferrer'
              >
                freecodecamp
              </a>
              <a
                className="hover:underline ml-1 text-blue-500"
                href="https://www.simplilearn.com/"
                target="_blank" rel='noreferrer'
              >
                ,simplilearn
              </a>{" "}
              <a
                className="hover:underline ml-1 text-blue-500"
                href="https://www.cisco.com/"
                target="_blank" rel='noreferrer'
              >
                ,cisco
              </a>
              <a
                className="hover:underline ml-1 text-blue-500"
                href="https://scrimba.com/"
                target="_blank" rel='noreferrer'
              >
                ,scrimba
              </a>
              ...etc. And in 2021 i joined a codecamp called{" "}
              <a
                className="hover:underline ml-1 text-blue-500"
                href="https://www.codeloccol.org/"
                target="_blank" rel='noreferrer'
              >
                codeloccol
              </a>
              . like you will see in my resume, that make&apos;s me do many project
              some of them can be check in my{" "}
              <a
                className="hover:underline ml-1 text-blue-500"
                href="https://github.com/Yacoubou-seidou"
                target="_blank" rel='noreferrer'
              >
                github
              </a>
              . All my github repository are from my training journey.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap justify-center ">
            <div className="growd basis-1/4 flex-4 ">
              <a
                href="https://yacoubou-seidou.github.io/Project-MI/"
                target="_blank" rel='noreferrer'
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                  alt="project"
                />
              </a>
            </div>
            <div className="growd basis-1/4 flex-4">
              <a
                href="https://yacoubou-seidou.github.io/searchBarAnimation/"
                target="_blank" rel='noreferrer'
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web2}
                  alt="project"
                />
              </a>
            </div>
            <div className="growd basis-1/4 flex-4">
              <a
                href="https://yacoubou-seidou.github.io/Chopping/"
                target="_blank" rel='noreferrer'
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web3}
                  alt="project"
                />
              </a>
            </div>
            <div className="growd basis-1/4 flex-4">
              <a
                href="https://yacoubou-seidou.github.io/Myadmin/"
                target="_blank" rel='noreferrer'
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web4}
                  alt="project"
                />
              </a>
            </div>
            <div className="growd basis-1/4 flex-4">
              <a
                href="https://yacoubou-seidou.github.io/Karanta/"
                target="_blank" rel='noreferrer'
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web5}
                  alt="project"
                />
              </a>
            </div>
            <div className="growd basis-1/4 flex-4">
              <a
                href="https://yacoubou-seidou.github.io/englishDictionnary/"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web6}
                  alt="project"
                />
              </a>
            </div>
          </div>
        </section>

        <footer className="bg-white dark:bg-gray-900">
          <div className="px-4 py-6 bg-gray-100 dark:bg-gray-700 md:flex md:items-center md:justify-between">
            <span className="text-sm text-gray-800 dark:text-gray-300 sm:text-center">
              © 2023{" "}
              <a
                href="https://www.linkedin.com/in/yacos-chaibou-961518251/"
                target="_blank"
                rel="noreferrer"
                className="hover:underline"
              >
                Yacoubou Seidou
              </a>
              . All Rights Reserved.
            </span>
            <div className="flex mt-4 space-x-6 sm:justify-center md:mt-0">
              <a
                href="https://www.facebook.com/Blackyacos.chaibou"
                className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
              >
                <svg
                  className="w-8 h-8"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path
                    fillRule="evenodd"
                    d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                    clipRule="evenodd"
                  />
                </svg>
                <span className="sr-only">Facebook page</span>
              </a>
              <a
                href="https://www.linkedin.com/in/yacos-chaibou-961518251/"
                className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
              >
                <svg
                  className="w-8 h-8"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path
                    fillRule="evenodd"
                    d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2 16h-2v-6h2v6zm-1-6.891c-.607 0-1.1-.496-1.1-1.109 0-.612.492-1.109 1.1-1.109s1.1.497 1.1 1.109c0 .613-.493 1.109-1.1 1.109zm8 6.891h-1.998v-2.861c0-1.881-2.002-1.722-2.002 0v2.861h-2v-6h2v1.093c.872-1.616 4-1.736 4 1.548v3.359z"
                    clipRule="evenodd"
                  />
                </svg>
                <span className="sr-only">Linkedin</span>
              </a>
              <a
                href="https://github.com/Yacoubou-seidou"
                className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
              >
                <svg
                  className="w-8 h-8"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path
                    fillRule="evenodd"
                    d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                    clipRule="evenodd"
                  />
                </svg>
                <span className="sr-only">GitHub account</span>
              </a>
            </div>
          </div>
        </footer>
      </main>
    </div>
  );
}
